// AUTO-GENERATED by WaratahCmd.exe

// HID Usage Tables: 1.4.0
// Descriptor size: 24 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 2 |
// +----------+-------+-------------------+
static const uint8_t hidReportDescriptor [] = 
{
    0x05, 0x02,          // UsagePage(Simulation Controls[0x0002])
    0x09, 0x02,          // UsageId(Automobile Simulation Device[0x0002])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x01,          //     ReportId(1)
    0x09, 0xC6,          //     UsageId(Clutch[0x00C6])
    0x09, 0xC6,          //     UsageId(Clutch[0x00C6])
    0x15, 0x00,          //     LogicalMinimum(0)
    0x26, 0xFF, 0x00,    //     LogicalMaximum(255)
    0x95, 0x02,          //     ReportCount(2)
    0x75, 0x08,          //     ReportSize(8)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                // EndCollection()
};

#pragma pack(push,1)

struct HidReportInput1
{
    uint8_t ReportId = 1;
    uint8_t Payload[2];
};

#pragma pack(pop)